### ISSUE TITLE
Android studio not highlighting dependencies

### ISSUE THREAD

**Issue by aoben10** [PicPay/version-checker-gradle-lint#2]
I executed the shell script, and verified the versionlint file was in buildSrc. but how do I get android studio to highlight older dependencies? What step am I missing? Does the lint version and dependencies have to live in different files? Or can they be in the same file as different singleton objects

Android Studio 4.1
Kotlin Gradle DSL

**Comment by jeziellago** [comment]
Hi @aoben10 
The current version of `VersionCheckerGradleLint` needs different files to `versions` and `libraries declaration`.
Example:
```kotlin
// file: Versions.kt
object Versions {

    val kotlinVersion = "1.4.10"
   
}
```

```kotlin
// file: Libs.kt
object Libs {

    val kotlin = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlinVersion}"
}
```

**Comment by jeziellago** [comment]
We'll consider declarations in a single file in the next versions.

**Comment by aoben10** [comment]
I see, thanks!
